<?php

namespace common\models\c2\entity;

use Yii;
use yii\validators\RequiredValidator;

/**
 * This is the model class for table "{{%product_package}}".
 *
 * @property string $id
 * @property string $product_id
 * @property string $name
 * @property string $label
 * @property integer $product_capacity
 * @property string $gross_weight
 * @property string $net_weight
 * @property string $memo
 * @property integer $status
 * @property integer $position
 * @property string $created_at
 * @property string $updated_at
 */
class ProductPackage extends \cza\base\models\ActiveRecord
{
    public $items;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product_package}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'product_capacity', 'position'], 'integer'],
            [['memo'], 'string'],
            [['created_at', 'updated_at', 'items'], 'safe'],
            [['items'], 'validateItems'],
            [['name', 'label', 'gross_weight', 'net_weight'], 'string', 'max' => 255],
            [['status'], 'integer', 'max' => 4],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app.c2', 'ID'),
            'product_id' => Yii::t('app.c2', 'Product ID'),
            'name' => Yii::t('app.c2', 'Name'),
            'label' => Yii::t('app.c2', 'Label'),
            'product_capacity' => Yii::t('app.c2', 'Product Capacity'),
            'gross_weight' => Yii::t('app.c2', 'Gross Weight'),
            'net_weight' => Yii::t('app.c2', 'Net Weight'),
            'memo' => Yii::t('app.c2', 'Memo'),
            'status' => Yii::t('app.c2', 'Status'),
            'position' => Yii::t('app.c2', 'Position'),
            'created_at' => Yii::t('app.c2', 'Created At'),
            'updated_at' => Yii::t('app.c2', 'Updated At'),
        ];
    }

    public function validateItems($attribute)
    {
        $items = $this->$attribute;

        foreach ($items as $index => $row) {
            $requiredValidator = new RequiredValidator();
            $error = null;
            $requiredValidator->validate($row['product_id'], $error);
            if (!empty($error)) {
                $key = $attribute . '[' . $index . '][product_id]';
                $this->addError($key, Yii::t('app.c2', '{attribute} can not be empty!', ['attribute' => Yii::t('app.c2', 'Product')]));
            }
        }
    }

    /**
     * @inheritdoc
     * @return \common\models\c2\query\ProductPackageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\c2\query\ProductPackageQuery(get_called_class());
    }
    
    /**
    * setup default values
    **/
    public function loadDefaultValues($skipIfSet = true) {
        parent::loadDefaultValues($skipIfSet);
    }

    public function getPackageItems()
    {
        return $this->hasMany(ProductPackageItem::className(), ['package_id' => 'id']);
    }

    public function loadItems()
    {
        $this->items = $this->getPackageItems()->all();
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if (!empty($this->items)) {
            foreach ($this->items as $item) {
                $attributes = [
                    'label' => isset($item['label']) ? $item['label'] : '',
                    'product_id' => isset($item['product_id']) ? $item['product_id'] : 0,
                    'need_number' => isset($item['need_number']) ? $item['need_number'] : 0,
                    'position' => isset($item['position']) ? $item['position'] : 0,
                ];
                if (isset($item['id']) && $item['id'] == '') {
                    $itemModel = new ProductPackageItem();
                    $itemModel->setAttributes($attributes);
                    $itemModel->link('owner', $this);
                } elseif (isset($item['id'])) {
                    $itemModel = ProductPackageItem::findOne($item['id']);
                    if (!is_null($itemModel)) {
                        $itemModel->updateAttributes($attributes);
                    }
                }
            }
        }
    }

    public function beforeDelete()
    {
        foreach ($this->getPackageItems()->all() as $item) {
            $item->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

}
