<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/5
 * Time: 12:09
 */

namespace backend\models\c2\entity;

use common\models\c2\entity\Product as BaseModel;
use common\models\c2\entity\WarehouseNote;
use common\models\c2\entity\WarehouseNoteItem;
use common\models\c2\statics\WarehouseNoteItemStatus;
use common\models\c2\statics\WarehouseNoteState;
use common\models\c2\statics\WarehouseNoteType;
use Yii;
use yii\helpers\ArrayHelper;

class Product extends BaseModel
{

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['sku'], 'unique'],
        ]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if (isset($changedAttributes['stock'])) {
            $warehouseNote = new WarehouseNote();
            $warehouseNote->type = WarehouseNoteType::MODIFY_BY_USER;
            $warehouseNote->state = WarehouseNoteState::COMMIT;
            if ($warehouseNote->save()) {
                $warehouseNoteItem = new WarehouseNoteItem();
                $warehouseNoteItem->note_id = $warehouseNote->id;
                $warehouseNoteItem->product_id = $this->id;
                $warehouseNoteItem->product_name = $this->name;
                $warehouseNoteItem->product_sku = $this->sku;
                $warehouseNoteItem->product_label = $this->label;
                $warehouseNoteItem->product_value = $this->value;
                $warehouseNoteItem->measure_id = $this->measure_id;
                $warehouseNoteItem->status = WarehouseNoteItemStatus::COMMIT;
                $warehouseNoteItem->number = $this->stock;
                $warehouseNoteItem->memo = "手动修改,修改前{$changedAttributes['stock']},修改后{$this->stock}";
                $warehouseNoteItem->save();
            }
        }
    }

}