<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace backend\components;

use DateTime;
use Yii;
use yii\helpers\Url;
use yii\base\InvalidRouteException;
use yii\web\NotFoundHttpException;

/**
 * Description of Application
 * @property \cza\base\helpers\Helper $czaHelper The request component. This property is read-only.
 * @author ben
 */
class Application extends \yii\web\Application {

    public $allowUsers = [
        '黄笑琼',
        '李婉莹',
        '卢泳岚',
    ];

    public function behaviors() {
        return [
//            'basicAuth' => [
//                'class' => \yii\filters\auth\HttpBasicAuth::className(),
//            ],

            [
                'class' => \yii\filters\ContentNegotiator::className(),
                'formats' => [
                    'text/html' => \yii\web\Response::FORMAT_HTML,
                    'application/json' => \yii\web\Response::FORMAT_JSON,
                    'application/xml' => \yii\web\Response::FORMAT_XML,
                ],
                'languages' => [
//                    'en-US',
                    'zh-CN',
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
//                'except' => ['debug/default/toolbar', 'debug/default/view'],
//                 'except' => ['debug*',],
                'except' => ['api*',],
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
//                        'actions' => ['logout', 'index', 'page'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'logout' => ['get', 'post'],
                ],
            ],
//            'action-time' => [
//                'class' => \cza\base\behaviors\ActionTimeFilter::className(),
//            ],
        ];
    }

    public function beforeAction($action)
    {

        $sys_open_at = Yii::$app->settings->get('sys_open_at', '8:00');
        $sys_close_at = Yii::$app->settings->get('sys_close_at', '19:00');
        // $sys_close_at = '13:00';

        if ($this->isSysClose($sys_open_at, $sys_close_at)) {
            $user = Yii::$app->user->identity;
            if ($user && !in_array($user->username, $this->allowUsers)) {
                Yii::$app->user->logout();
                Yii::$app->response->content = "Resting";
                return false;
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function isSysClose($time1, $time2)
    {
        // 定义起始和结束时间
        // $time1 = '08:30'; // 次日的结束时间
        // $time2 = '19:00'; // 当日的起始时间

        // 获取当前时间
        // $current_time = new DateTime();
        $current_time = time();

        // 创建当天的 $time2 对象
        $time2_today = new DateTime($time2);
        $time2_today = $time2_today->getTimestamp();

        // 创建次日的 $time1 对象
        $time1_next_day = new DateTime($time1);
        $time1_next_day->modify('+1 day');
        $time1_next_day = $time1_next_day->getTimestamp();

        if ($current_time >= $time2_today && $current_time <= $time1_next_day) {
            return true;
        }

        return false;
    }

    /**
     * correct wrong bower path
     * @param string $path the directory that stores vendor files.
     */
    public function setVendorPath($path) {
        parent::setVendorPath($path);
        Yii::setAlias('@bower', $this->getVendorPath() . DIRECTORY_SEPARATOR . 'bower-asset');
    }

}
