<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace backend\components;

use DateTime;
use Yii;
use yii\helpers\Url;
use yii\base\InvalidRouteException;
use yii\web\NotFoundHttpException;

/**
 * Description of Application
 * @property \cza\base\helpers\Helper $czaHelper The request component. This property is read-only.
 * @author ben
 */
class Application extends \yii\web\Application {

    public $allowUsers = [
        '黄笑琼',
        '李婉莹',
        '卢泳岚',
    ];

    public function behaviors() {
        return [
//            'basicAuth' => [
//                'class' => \yii\filters\auth\HttpBasicAuth::className(),
//            ],

            [
                'class' => \yii\filters\ContentNegotiator::className(),
                'formats' => [
                    'text/html' => \yii\web\Response::FORMAT_HTML,
                    'application/json' => \yii\web\Response::FORMAT_JSON,
                    'application/xml' => \yii\web\Response::FORMAT_XML,
                ],
                'languages' => [
//                    'en-US',
                    'zh-CN',
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
//                'except' => ['debug/default/toolbar', 'debug/default/view'],
//                 'except' => ['debug*',],
                'except' => ['api*',],
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
//                        'actions' => ['logout', 'index', 'page'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'logout' => ['get', 'post'],
                ],
            ],
//            'action-time' => [
//                'class' => \cza\base\behaviors\ActionTimeFilter::className(),
//            ],
        ];
    }

    public function beforeAction($action)
    {

        $sys_open_at = Yii::$app->settings->get('sys_open_at', '07:30');
        $sys_close_at = Yii::$app->settings->get('sys_close_at', '20:00');
        // $sys_close_at = '13:00';

        if ($this->isSysClose($sys_open_at, $sys_close_at)) {
            $user = Yii::$app->user->identity;
            if ($user && !in_array($user->username, $this->allowUsers)) {
                Yii::$app->user->logout();
                Yii::$app->response->content = "现在是休息时间，系统进行夜间维护，时间为每天晚上$sys_close_at - 次日$sys_open_at";
                return false;
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function isSysClose($openAt, $closeAt)
    {
        $current = date('H:i');

        // 正常情况，例如 08:00 ~ 20:00
        if ($openAt < $closeAt) {
            return $current < $openAt || $current >= $closeAt;
        }

        // 跨午夜，例如 20:00 ~ 次日 08:00
        return $current >= $closeAt || $current < $openAt;
    }

    /**
     * correct wrong bower path
     * @param string $path the directory that stores vendor files.
     */
    public function setVendorPath($path) {
        parent::setVendorPath($path);
        Yii::setAlias('@bower', $this->getVendorPath() . DIRECTORY_SEPARATOR . 'bower-asset');
    }

}
